{% set name = "sklearn-pandas" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sklearn-pandas-{{ version }}.tar.gz
  sha256: f86c4afc18891ae565af8ee47b6cc84553c410436cbf670be25a199817187831

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - scikit-learn>=0.23.0
    - scipy>=1.5.1
    - pandas>=1.1.4
    - numpy>=1.18.1

test:
  imports:
    - sklearn_pandas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-learn-contrib/sklearn-pandas
  summary: Pandas integration with sklearn
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
    - ragrawal
